/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes/index'
import { Route as QuizzesQuizIdRouteImport } from './routes/quizzes/$quizId'
import { Route as QuizzesQuizIdIndexRouteImport } from './routes/quizzes/$quizId/index'
import { Route as QuizzesQuizIdResultsRouteImport } from './routes/quizzes/$quizId/results'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdRoute = QuizzesQuizIdRouteImport.update({
  id: '/quizzes/$quizId',
  path: '/quizzes/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdIndexRoute = QuizzesQuizIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizzesQuizIdRoute,
} as any)
const QuizzesQuizIdResultsRoute = QuizzesQuizIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => QuizzesQuizIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRouteWithChildren
  '/quizzes': typeof QuizzesIndexRoute
  '/quizzes/$quizId/results': typeof QuizzesQuizIdResultsRoute
  '/quizzes/$quizId/': typeof QuizzesQuizIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/quizzes/$quizId/results': typeof QuizzesQuizIdResultsRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRouteWithChildren
  '/quizzes/': typeof QuizzesIndexRoute
  '/quizzes/$quizId/results': typeof QuizzesQuizIdResultsRoute
  '/quizzes/$quizId/': typeof QuizzesQuizIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/quizzes/$quizId'
    | '/quizzes'
    | '/quizzes/$quizId/results'
    | '/quizzes/$quizId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/quizzes'
    | '/quizzes/$quizId/results'
    | '/quizzes/$quizId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/quizzes/$quizId'
    | '/quizzes/'
    | '/quizzes/$quizId/results'
    | '/quizzes/$quizId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  QuizzesQuizIdRoute: typeof QuizzesQuizIdRouteWithChildren
  QuizzesIndexRoute: typeof QuizzesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId': {
      id: '/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof QuizzesQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId/': {
      id: '/quizzes/$quizId/'
      path: '/'
      fullPath: '/quizzes/$quizId/'
      preLoaderRoute: typeof QuizzesQuizIdIndexRouteImport
      parentRoute: typeof QuizzesQuizIdRoute
    }
    '/quizzes/$quizId/results': {
      id: '/quizzes/$quizId/results'
      path: '/results'
      fullPath: '/quizzes/$quizId/results'
      preLoaderRoute: typeof QuizzesQuizIdResultsRouteImport
      parentRoute: typeof QuizzesQuizIdRoute
    }
  }
}

interface QuizzesQuizIdRouteChildren {
  QuizzesQuizIdResultsRoute: typeof QuizzesQuizIdResultsRoute
  QuizzesQuizIdIndexRoute: typeof QuizzesQuizIdIndexRoute
}

const QuizzesQuizIdRouteChildren: QuizzesQuizIdRouteChildren = {
  QuizzesQuizIdResultsRoute: QuizzesQuizIdResultsRoute,
  QuizzesQuizIdIndexRoute: QuizzesQuizIdIndexRoute,
}

const QuizzesQuizIdRouteWithChildren = QuizzesQuizIdRoute._addFileChildren(
  QuizzesQuizIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  QuizzesQuizIdRoute: QuizzesQuizIdRouteWithChildren,
  QuizzesIndexRoute: QuizzesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
